---

- name: Transfer red alert sound file to server
  copy:
    src: "/opt/stackstorm/packs/st2_chatops_aliases/playbooks/roles/red_alert/files/red_alert.{{ item }}"
    dest: /var/lib/asterisk/sounds
    owner: root
    group: asterisk
    mode: 0664
  with_items:
   - gsm
   - alaw
   - wav
   - ulaw
   - g722
   - sln
   - g729

- name: Generate template file on server
  template:
    src: "/opt/stackstorm/packs/st2_chatops_aliases/playbooks/roles/red_alert/templates/red_alert-{{ item }}.j2"
    dest: "/opt/stackstorm/packs/st2_chatops_aliases/playbooks/roles/red_alert/files/red_alert-{{ item }}.call"
    owner: root
    group: st2packs
    mode: 0664
  with_items: "{{ destinations }}"
  delegate_to: localhost

- name: Transfer template file to asterisk
  copy:
    src: "/opt/stackstorm/packs/st2_chatops_aliases/playbooks/roles/red_alert/files/red_alert-{{ item }}.call"
    dest: "/var/spool/asterisk/outgoing/red_alert-{{ item }}.call"
    owner: root
    group: asterisk
    mode: 0664
  with_items: "{{ destinations }}"
