---

- name: Transfer red alert sound file to server
  copy:
    src: "/opt/stackstorm/packs/st2_chatops_aliases/playbooks/roles/red_alert/files/red_alert.{{ item }}"
    dest: /var/lib/asterisk/sounds
    owner: root
    group: asterisk
    mode: 0664
  with_items:
  #  - gsm
  #  - alaw
   - wav
  #  - ulaw

- name: Transfer template to server
  template:
    src: /opt/stackstorm/packs/st2_chatops_aliases/playbooks/roles/red_alert/templates/red_alert.j2
    dest: /var/spool/asterisk/outgoing
    owner: root
    group: asterisk
    mode: 0664
