---

  - name: Transfer red alert sound file to server
    src: "files/red_alert.{{ item }}"
    dest: /var/lib/asterisk/sounds
    owner: root
    group: asterisk
    mode: 0664
    with_items:
    #  - gsm
    #  - alaw
     - wav
    #  - ulaw

  - name: Transfer template to server
    src: templates/red_alert.j2
    dest: /var/spool/asterisk/outgoing
    owner: root
    group: asterisk
    mode: 0664
